### ISSUE TITLE
Saving user inputs for (complex) shiny plots?

### ISSUE THREAD

**Issue by wptmdoorn** [tercen/template_shiny_operator#4]
It would be very helpful to have data storage functionality for user inputs in Shiny apps when creating plots. This is especially important in more complex plots with a magnitude of parameters. Has anyone touched upon this before? An interesting read might be:

https://shiny.rstudio.com/articles/persistent-data-storage.html

Thoughts? 

PS. I am not sure if this should be on this GitHub or on the tercen/sci one (but I do not have access to that yet).

Thanks, William

**Comment by ginberg** [comment]
hi William, that sounds useful! I have saved user inputs for later use, using rds files or [shiny bookmarking](https://shiny.rstudio.com/articles/bookmarking-state.html), but that was for apps developed outside of Tercen.

The way shiny apps are run on Tercen, via the R command line inside a docker container, limits us a bit in the options. I think, an external database like sqlite could work since the data will not be lost when you restart the app/container. I noticed other people are using [that approach](https://stackoverflow.com/questions/51352921/database-not-stored-on-docker-image-with-shinyproxy), though that post is about shinyproxy. 
I think it's good to discuss this with @amaurel

**Comment by amaurel** [comment]
You will find an example on how to store user inputs for gui parameters in this repo
https://github.com/tercen/shiny_operator2

**Comment by amaurel** [comment]
The idea is that one or more files can be attached to a step, when the step is deleted the files are also deleted.

**Comment by amaurel** [comment]
`
files = ctx$client$fileService$findFileByWorkflowIdAndStepId(    startKey=list(workflowId,stepId),    endKey=list(workflowId,''),    descending=TRUE, limit=1 )
`

**Comment by ginberg** [comment]
ah, I didn't know that operator, great you already got a solution for storing user inputs
